INSERT INTO dbo.Products (Name, Description, Price, QuantityInStock, Category)
VALUES
('Wireless Charger', 'Qi-certified wireless charging pad compatible with most smartphones.', 19.99, 110, 'Electronics'),
('Smartphone Case', 'Shockproof TPU phone case available for various models.', 12.50, 200, 'Electronics'),
('LED Monitor 24"', '24-inch Full HD LED monitor with HDMI and VGA ports.', 129.99, 40, 'Electronics'),
('Portable Bluetooth Speaker', 'Compact speaker with deep bass and 12-hour battery life.', 45.00, 75, 'Electronics'),
('Mechanical Pencil', '0.5mm mechanical pencil with refillable leads.', 2.99, 320, 'Stationery'),
('Sticky Notes', 'Pack of 6 colorful sticky note pads, 100 sheets each.', 5.49, 250, 'Stationery'),
('Desk Organizer', 'Multi-compartment desk organizer with pen holder and trays.', 14.99, 85, 'Office Supplies'),
('USB Flash Drive 64GB', 'High-speed USB 3.0 flash drive with 64GB capacity.', 22.99, 130, 'Electronics'),
('Wireless Keyboard', 'Slim wireless keyboard with rechargeable battery.', 39.99, 70, 'Electronics'),
('Paper Clips Box', 'Box of 100 metal paper clips for office use.', 1.29, 400, 'Stationery'),
('Electric Kettle', '1.7L electric kettle with auto shut-off and boil-dry protection.', 29.99, 50, 'Home & Kitchen'),
('Ceramic Plate Set', 'Set of 6 ceramic dinner plates, dishwasher safe.', 49.99, 60, 'Home & Kitchen'),
('Desk Calendar 2025', 'Desk calendar with monthly view and space for notes.', 7.99, 90, 'Stationery'),
('Fitness Dumbbells Set', 'Pair of 5kg neoprene dumbbells for strength training.', 29.95, 55, 'Fitness'),
('Running Shoes', 'Lightweight running shoes with breathable mesh upper.', 69.99, 45, 'Fitness'),
('Noise Cancelling Earbuds', 'In-ear wireless earbuds with active noise cancellation.', 59.99, 80, 'Electronics'),
('Laptop Backpack', 'Water-resistant laptop backpack with multiple compartments.', 54.99, 70, 'Accessories'),
('Desk Chair Mat', 'Clear vinyl mat to protect floors from chair wheels.', 24.99, 100, 'Office Supplies'),
('HDMI Cable 2m', 'High-speed HDMI cable supporting 4K resolution.', 9.99, 150, 'Electronics'),
('Smartwatch', 'Smartwatch with heart rate monitor and step counter.', 89.95, 60, 'Electronics'),
('Wall Clock', 'Modern wall clock with silent quartz movement.', 19.99, 75, 'Home & Kitchen'),
('Leather Wallet', 'Genuine leather bifold wallet with multiple card slots.', 34.99, 85, 'Accessories'),
('Bluetooth Mouse', 'Compact Bluetooth mouse with ergonomic design.', 24.99, 110, 'Electronics'),
('Rechargeable Flashlight', 'LED flashlight with rechargeable battery and adjustable beam.', 22.50, 95, 'Home & Kitchen'),
('Coffee Maker', '12-cup drip coffee maker with programmable timer.', 79.99, 40, 'Home & Kitchen'),
('Smart Light Switch', 'Wi-Fi enabled smart light switch compatible with Alexa and Google Home.', 39.99, 80, 'Home Automation'),
('Yoga Block', 'Foam yoga block for enhanced support and flexibility.', 14.99, 90, 'Fitness'),
('Electric Toothbrush', 'Rechargeable electric toothbrush with multiple brushing modes.', 49.99, 70, 'Personal Care'),
('Waterproof Phone Pouch', 'Universal waterproof phone pouch with secure seal.', 9.99, 120, 'Accessories'),
('Notebook Stand', 'Adjustable wooden notebook stand for desk use.', 29.95, 65, 'Office Supplies'),
('Digital Kitchen Scale', 'Compact kitchen scale with LCD display and tare function.', 19.95, 85, 'Home & Kitchen');
